<a href="https://colab.research.google.com/github/aparnaprakash287/python_and_libraries/blob/main/Pandas/_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Series

A Series is a 1D labeled array capable of holding any data type.

**Types of Series**

Integer Series

Float Series

String Series

Mixed Data Series

Series from Dictionary

In [ ]:
import pandas as pd
a=pd.Series([1,2334,25,66,876])# Integer Series

In [ ]:
a

0       1
1    2334
2      25
3      66
4     876
dtype: int64

In [ ]:
m=pd.Series([1.2,3.3342,4.243])# Float Series

In [ ]:
m

0    1.2000
1    3.3342
2    4.2430
dtype: float64

In [ ]:
n=pd.Series(["a","s",12,2.3,"e"])# Mixed Series

In [ ]:
n

0      a
1      s
2     12
3    2.3
4      e
dtype: object

In [ ]:
# String Series
s3 = pd.Series(["A", "B", "C"])

# From Dictionary
s5 = pd.Series({'a':10, 'b':20, 'c':30})
s3
s5

a    10
b    20
c    30
dtype: int64

### **2. DATAFRAME**

A DataFrame is a 2D table with rows and columns.

🧩 Ways to Create DataFrame

From Dictionary

From List of Lists

From List of Dictionaries

From Series

From NumPy Array

In [ ]:
import numpy as np

# From dict
df1 = pd.DataFrame({'Name': ['A','B'], 'Age':[20,25]})
df1

  Name  Age
0    A   20
1    B   25

In [ ]:
import pandas as pd
a=pd.DataFrame([{'a':2},{"b":3}])
a

     a    b
0  2.0  NaN
1  NaN  3.0

In [ ]:
import pandas as pd
w=pd.DataFrame({"name":["aparna","sneha"],"age":[22,21]})
w

     name  age
0  aparna   22
1   sneha   21

In [ ]:
w.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    2 non-null      object
 1   age     2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes

In [ ]:
w.describe()

             age
count   2.000000
mean   21.500000
std     0.707107
min    21.000000
25%    21.250000
50%    21.500000
75%    21.750000
max    22.000000

In [ ]:
w.shape

(2, 2)

In [ ]:
w.dtypes

name    object
age      int64
dtype: object

In [ ]:
import pandas as pd
c=pd.DataFrame({"name":["A","B","C","D"],"age":[22,21,23,32],"place":["kerala","mumbai","goa","TN"]})
c

  name  age   place
0    A   22  kerala
1    B   21  mumbai
2    C   23     goa
3    D   32      TN

# **3. READ FUNCTIONS**

1. pd.read_csv()	Read CSV file
2. pd.read_excel()	Read Excel file
3. pd.read_json()	Read JSON file
4. pd.read_html()	Read HTML tables
5. pd.read_sql()	Read from SQL
6. pd.read_clipboard()	Read copied data
7. pd.read_pickle()	Read Pickle file

In [ ]:
data=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/data (2).csv")
data

NameError: name 'pd' is not defined

In [ ]:
a=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/aapl_sample.csv")
a

In [ ]:
a.head(2)

In [ ]:
a.tail(3)

# **4. PREPROCESSING FUNCTIONS**

## Renaming Columns

In [ ]:
import pandas as pd
c=pd.DataFrame({"name":["A","B","C","D"],"age":[22,21,23,32],"place":["kerala","mumbai","goa","TN"]})
c

In [ ]:
c.rename(columns={'name':'Student_Name'}, inplace=True)
c

## Changing Data Type

In [ ]:
c.info()

In [ ]:
c['age'] = c['age'].astype(float)
c

## Handling Missing Values

In [ ]:
import pandas as pd
n=pd.read_csv("/content/employees.csv")
n

  EmployeeID           Name   Department   Age   Salary    JoinDate
0       E001     John Smith        Sales  29.0  55000.0  2018-03-15
1       E002  Sarah Johnson           HR   NaN  62000.0  2019-06-10
2       E003    Michael Lee  Engineering  35.0      NaN  2017-11-05
3       E004            NaN    Marketing  28.0  48000.0  2020-01-20
4       E005    Emily Davis  Engineering   NaN  71000.0         NaN
5       E006   David Wilson          NaN  42.0  68000.0  2016-08-12
6       E007   Amanda Brown        Sales  31.0      NaN         NaN
7       E008  Robert Taylor      Finance  45.0  83000.0  2015-02-25
8       E009            NaN           HR  38.0  59000.0  2018-12-30
9       E010   Linda Harris    Marketing   NaN      NaN         NaN

In [ ]:
n.fillna(0,inplace=True)
n

  EmployeeID           Name   Department   Age   Salary    JoinDate
0       E001     John Smith        Sales  29.0  55000.0  2018-03-15
1       E002  Sarah Johnson           HR   0.0  62000.0  2019-06-10
2       E003    Michael Lee  Engineering  35.0      0.0  2017-11-05
3       E004              0    Marketing  28.0  48000.0  2020-01-20
4       E005    Emily Davis  Engineering   0.0  71000.0           0
5       E006   David Wilson            0  42.0  68000.0  2016-08-12
6       E007   Amanda Brown        Sales  31.0      0.0           0
7       E008  Robert Taylor      Finance  45.0  83000.0  2015-02-25
8       E009              0           HR  38.0  59000.0  2018-12-30
9       E010   Linda Harris    Marketing   0.0      0.0           0

## Replacing Values

In [ ]:
n["Name"].replace(0,"Aparna",inplace=True)

/tmp/ipython-input-2133339762.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  n["Name"].replace(0,"Aparna",inplace=True)

In [ ]:
n

  EmployeeID           Name   Department   Age   Salary    JoinDate
0       E001     John Smith        Sales  29.0  55000.0  2018-03-15
1       E002  Sarah Johnson           HR   0.0  62000.0  2019-06-10
2       E003    Michael Lee  Engineering  35.0      0.0  2017-11-05
3       E004         Aparna    Marketing  28.0  48000.0  2020-01-20
4       E005    Emily Davis  Engineering   0.0  71000.0           0
5       E006   David Wilson            0  42.0  68000.0  2016-08-12
6       E007   Amanda Brown        Sales  31.0      0.0           0
7       E008  Robert Taylor      Finance  45.0  83000.0  2015-02-25
8       E009         Aparna           HR  38.0  59000.0  2018-12-30
9       E010   Linda Harris    Marketing   0.0      0.0           0

## creating features

In [ ]:
n["total salary"]=n["Salary"]+5000
n

,EmployeeID,Name,Department,Age,Salary,JoinDate,total salary
0,E001,John Smith,Sales,29.0,55000.0,2018-03-15,60000.0
1,E002,Sarah Johnson,HR,0.0,62000.0,2019-06-10,67000.0
2,E003,Michael Lee,Engineering,35.0,0.0,2017-11-05,5000.0
3,E004,Aparna,Marketing,28.0,48000.0,2020-01-20,53000.0
4,E005,Emily Davis,Engineering,0.0,71000.0,0,76000.0
5,E006,David Wilson,0,42.0,68000.0,2016-08-12,73000.0
6,E007,Amanda Brown,Sales,31.0,0.0,0,5000.0
7,E008,Robert Taylor,Finance,45.0,83000.0,2015-02-25,88000.0
8,E009,Aparna,HR,38.0,59000.0,2018-12-30,64000.0
9,E010,Linda Harris,Marketing,0.0,0.0,0,5000.0

In [ ]:
import pandas as pd
df=pd.read_csv("/content/employees.csv")
df

  EmployeeID           Name   Department   Age   Salary    JoinDate
0       E001     John Smith        Sales  29.0  55000.0  2018-03-15
1       E002  Sarah Johnson           HR   NaN  62000.0  2019-06-10
2       E003    Michael Lee  Engineering  35.0      NaN  2017-11-05
3       E004            NaN    Marketing  28.0  48000.0  2020-01-20
4       E005    Emily Davis  Engineering   NaN  71000.0         NaN
5       E006   David Wilson          NaN  42.0  68000.0  2016-08-12
6       E007   Amanda Brown        Sales  31.0      NaN         NaN
7       E008  Robert Taylor      Finance  45.0  83000.0  2015-02-25
8       E009            NaN           HR  38.0  59000.0  2018-12-30
9       E010   Linda Harris    Marketing   NaN      NaN         NaN

In [ ]:
df.dropna()

  EmployeeID           Name Department   Age   Salary    JoinDate
0       E001     John Smith      Sales  29.0  55000.0  2018-03-15
7       E008  Robert Taylor    Finance  45.0  83000.0  2015-02-25

In [ ]:
df=pd.read_csv("/content/employees.csv")
df

  EmployeeID           Name   Department   Age   Salary    JoinDate
0       E001     John Smith        Sales  29.0  55000.0  2018-03-15
1       E002  Sarah Johnson           HR   NaN  62000.0  2019-06-10
2       E003    Michael Lee  Engineering  35.0      NaN  2017-11-05
3       E004            NaN    Marketing  28.0  48000.0  2020-01-20
4       E005    Emily Davis  Engineering   NaN  71000.0         NaN
5       E006   David Wilson          NaN  42.0  68000.0  2016-08-12
6       E007   Amanda Brown        Sales  31.0      NaN         NaN
7       E008  Robert Taylor      Finance  45.0  83000.0  2015-02-25
8       E009            NaN           HR  38.0  59000.0  2018-12-30
9       E010   Linda Harris    Marketing   NaN      NaN         NaN

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.groupby("Department")["Salary"].max()

Department
Engineering    71000.0
Finance        83000.0
HR             62000.0
Marketing      48000.0
Sales          55000.0
Name: Salary, dtype: float64

In [ ]:
df=pd.read_csv("/content/airline_dataset.csv")
df

               Airline  Price (USD)  Duration (hours)   Destination
0            Air India          520               9.5      New York
1             Emirates          670               3.2         Dubai
2        Qatar Airways          640               4.1          Doha
3   Singapore Airlines          750               5.6     Singapore
4      British Airways          590               8.0        London
5            Lufthansa          610               7.5     Frankfurt
6               IndiGo          120               1.5        Mumbai
7              Vistara          140               2.0         Delhi
8       Etihad Airways          630               4.0     Abu Dhabi
9         Thai Airways          710               4.8       Bangkok
10      Cathay Pacific          760               6.0     Hong Kong
11    Turkish Airlines          580               7.2      Istanbul
12     United Airlines          540               9.0       Chicago
13   American Airlines          530               8.7   Los Angeles
14            SpiceJet          100               1.3           Goa
15               GoAir           90               1.0     Hyderabad
16             AirAsia          180               3.0  Kuala Lumpur
17            Oman Air          600               3.8        Muscat
18     KLM Royal Dutch          650               8.5     Amsterdam
19   Malaysia Airlines          720               5.2  Kuala Lumpur

In [ ]:
grp=df.groupby("Destination")
grp.get_group("Mumbai")

  Airline  Price (USD)  Duration (hours) Destination
6  IndiGo          120               1.5      Mumbai

In [ ]:
df.groupby("Airline")["Price (USD)"].max()

Airline
Air India             520
AirAsia               180
American Airlines     530
British Airways       590
Cathay Pacific        760
Emirates              670
Etihad Airways        630
GoAir                  90
IndiGo                120
KLM Royal Dutch       650
Lufthansa             610
Malaysia Airlines     720
Oman Air              600
Qatar Airways         640
Singapore Airlines    750
SpiceJet              100
Thai Airways          710
Turkish Airlines      580
United Airlines       540
Vistara               140
Name: Price (USD), dtype: int64

In [ ]:
df=pd.read_csv("/content/airline_dataset.csv")
df.groupby("Airline")["Duration (hours)"].max()

Airline
Air India             9.5
AirAsia               3.0
American Airlines     8.7
British Airways       8.0
Cathay Pacific        6.0
Emirates              3.2
Etihad Airways        4.0
GoAir                 1.0
IndiGo                1.5
KLM Royal Dutch       8.5
Lufthansa             7.5
Malaysia Airlines     5.2
Oman Air              3.8
Qatar Airways         4.1
Singapore Airlines    5.6
SpiceJet              1.3
Thai Airways          4.8
Turkish Airlines      7.2
United Airlines       9.0
Vistara               2.0
Name: Duration (hours), dtype: float64

## Concat
It is used to concat two or more dataframes

In [ ]:
import pandas as pd

In [ ]:
tcs={'id':[101,102,103,104],'name':['Mithun','Dipin','Jose','Rahul'],
     'Age':[25,26,27,29]}

wipro={'id':[101,102,103,104],
       'name':['dev','sreenath','sreerag','shafeel'],
       'age':[24,24,27,26]}
tcs_emp=pd.DataFrame(tcs)
tcs_emp

    id    name  Age
0  101  Mithun   25
1  102   Dipin   26
2  103    Jose   27
3  104   Rahul   29

In [ ]:
wipro_emp=pd.DataFrame(wipro)
wipro_emp

    id      name  age
0  101       dev   24
1  102  sreenath   24
2  103   sreerag   27
3  104   shafeel   26

In [ ]:
pd.concat([tcs_emp,wipro_emp])

    id      name   Age   age
0  101    Mithun  25.0   NaN
1  102     Dipin  26.0   NaN
2  103      Jose  27.0   NaN
3  104     Rahul  29.0   NaN
0  101       dev   NaN  24.0
1  102  sreenath   NaN  24.0
2  103   sreerag   NaN  27.0
3  104   shafeel   NaN  26.0

In [ ]:
#ignore index-To get common index after concatenation
pd.concat([tcs_emp,wipro_emp],ignore_index=True)

    id      name   Age   age
0  101    Mithun  25.0   NaN
1  102     Dipin  26.0   NaN
2  103      Jose  27.0   NaN
3  104     Rahul  29.0   NaN
4  101       dev   NaN  24.0
5  102  sreenath   NaN  24.0
6  103   sreerag   NaN  27.0
7  104   shafeel   NaN  26.0

In [ ]:
#keys-To provide seperate keys for each concatenate data frames
data=pd.concat([tcs_emp,wipro_emp],keys=["tcs","wipro"])
data

          id      name   Age   age
tcs   0  101    Mithun  25.0   NaN
      1  102     Dipin  26.0   NaN
      2  103      Jose  27.0   NaN
      3  104     Rahul  29.0   NaN
wipro 0  101       dev   NaN  24.0
      1  102  sreenath   NaN  24.0
      2  103   sreerag   NaN  27.0
      3  104   shafeel   NaN  26.0

In [ ]:
#concatenating vertically
data=pd.concat([tcs_emp,wipro_emp],axis=1)
data

    id    name  Age   id      name  age
0  101  Mithun   25  101       dev   24
1  102   Dipin   26  102  sreenath   24
2  103    Jose   27  103   sreerag   27
3  104   Rahul   29  104   shafeel   26

In [ ]:
#cocatinating a dataframe with a series
salary=pd.Series([65000,78000,30000],name="salary")
pd.concat([tcs_emp,salary],axis=1)

    id    name  Age   salary
0  101  Mithun   25  65000.0
1  102   Dipin   26  78000.0
2  103    Jose   27  30000.0
3  104   Rahul   29      NaN

## Merge
Merge is a process to merge two tables horizontally

In [ ]:
tcs={'id':[101,102,103,104],'name':['Mithun','Dipin','Jose','Rahul'],
     'age':[25,26,27,29]}

wipro={'id':[101,102,103,104],
       'name':['dev','sreenath','sreerag','shafeel'],
       'age':[24,24,27,26]}

tcs_emp=pd.DataFrame(tcs)
wipro_emp=pd.DataFrame(wipro)

tcs_emp

    id    name  age
0  101  Mithun   25
1  102   Dipin   26
2  103    Jose   27
3  104   Rahul   29

In [ ]:
wipro_emp

    id      name  age
0  101       dev   24
1  102  sreenath   24
2  103   sreerag   27
3  104   shafeel   26

In [ ]:
pd.merge(tcs_emp,wipro_emp,on="id")

    id  name_x  age_x    name_y  age_y
0  101  Mithun     25       dev     24
1  102   Dipin     26  sreenath     24
2  103    Jose     27   sreerag     27
3  104   Rahul     29   shafeel     26

In [ ]:
pd.merge(tcs_emp,wipro_emp,on="id",suffixes=["left","rigght"])

    id nameleft  ageleft namerigght  agerigght
0  101   Mithun       25        dev         24
1  102    Dipin       26   sreenath         24
2  103     Jose       27    sreerag         27
3  104    Rahul       29    shafeel         26

In [ ]:
pd.merge(tcs_emp,wipro_emp,on="id",how="outer")#outer join

    id  name_x  Age    name_y  age
0  101  Mithun   25       dev   24
1  102   Dipin   26  sreenath   24
2  103    Jose   27   sreerag   27
3  104   Rahul   29   shafeel   26

In [ ]:
pd.merge(tcs_emp,wipro_emp,on="age",how="outer")#merge on the basis of age and displays the result having same age

    id_x  name_x  age   id_y    name_y
0    NaN     NaN   24  101.0       dev
1    NaN     NaN   24  102.0  sreenath
2  101.0  Mithun   25    NaN       NaN
3  102.0   Dipin   26  104.0   shafeel
4  103.0    Jose   27  103.0   sreerag
5  104.0   Rahul   29    NaN       NaN

In [ ]:
import pandas as pd
data=pd.read_csv("/content/sample_data/weather_dataset (3).csv")
data

,Date,City,Temperature,Humidity,Wind Speed (km/h),Weather Condition
0,2025-11-01,New Delhi,28,45,12,Sunny
1,2025-11-01,Mumbai,32,70,8,Humid
2,2025-11-01,Bangalore,25,65,10,Cloudy
3,2025-11-01,Chennai,33,75,14,Hot
4,2025-11-01,Kolkata,30,68,9,Partly Cloudy
5,2025-11-02,New Delhi,27,48,10,Sunny
6,2025-11-02,Mumbai,31,72,7,Humid
7,2025-11-02,Bangalore,24,60,11,Drizzle
8,2025-11-02,Chennai,34,78,16,Hot
9,2025-11-02,Kolkata,29,70,8,Rainy
10,2025-11-03,New Delhi,26,50,13,Clear
11,2025-11-03,Mumbai,30,68,6,Sunny
12,2025-11-03,Bangalore,23,66,12,Thunderstorms
13,2025-11-03,Chennai,32,80,15,Humid
14,2025-11-03,Kolkata,28,72,10,Cloudy
15,2025-11-04,New Delhi,25,55,9,Foggy
16,2025-11-04,Mumbai,29,75,7,Overcast
17,2025-11-04,Bangalore,24,64,8,Cloudy
18,2025-11-04,Chennai,33,77,14,Sunny
19,2025-11-04,Kolkata,30,69,11,Partly Cloudy

In [ ]:
data.pivot(index='Date',columns='City') #create a table with date as index and city as columns

           Temperature                                   Humidity          \
City         Bangalore Chennai Kolkata Mumbai New Delhi Bangalore Chennai
Date
2025-11-01          25      33      30     32        28        65      75
2025-11-02          24      34      29     31        27        60      78
2025-11-03          23      32      28     30        26        66      80
2025-11-04          24      33      30     29        25        64      77

                                    Wind Speed (km/h)                         \
City       Kolkata Mumbai New Delhi         Bangalore Chennai Kolkata Mumbai
Date
2025-11-01      68     70        45                10      14       9      8
2025-11-02      70     72        48                11      16       8      7
2025-11-03      72     68        50                12      15      10      6
2025-11-04      69     75        55                 8      14      11      7

                     Weather Condition                                   \
City       New Delhi         Bangalore Chennai        Kolkata    Mumbai
Date
2025-11-01        12            Cloudy     Hot  Partly Cloudy     Humid
2025-11-02        10           Drizzle     Hot          Rainy     Humid
2025-11-03        13     Thunderstorms   Humid         Cloudy     Sunny
2025-11-04         9            Cloudy   Sunny  Partly Cloudy  Overcast


City       New Delhi
Date
2025-11-01     Sunny
2025-11-02     Sunny
2025-11-03     Clear
2025-11-04     Foggy

In [ ]:
data.pivot(index="Date",columns="City",values="Temperature")

City        Bangalore  Chennai  Kolkata  Mumbai  New Delhi
Date
2025-11-01         25       33       30      32         28
2025-11-02         24       34       29      31         27
2025-11-03         23       32       28      30         26
2025-11-04         24       33       30      29         25

In [ ]:
data.pivot_table(index="City",columns="Date",aggfunc='sum')

            Humidity                                  Temperature             \
Date      2025-11-01 2025-11-02 2025-11-03 2025-11-04  2025-11-01 2025-11-02
City
Bangalore         65         60         66         64          25         24
Chennai           75         78         80         77          33         34
Kolkata           68         70         72         69          30         29
Mumbai            70         72         68         75          32         31
New Delhi         45         48         50         55          28         27

                                Weather Condition                            \
Date      2025-11-03 2025-11-04        2025-11-01 2025-11-02     2025-11-03
City
Bangalore         23         24            Cloudy    Drizzle  Thunderstorms
Chennai           32         33               Hot        Hot          Humid
Kolkata           28         30     Partly Cloudy      Rainy         Cloudy
Mumbai            30         29             Humid      Humid          Sunny
New Delhi         26         25             Sunny      Sunny          Clear

                         Wind Speed (km/h)
Date          2025-11-04        2025-11-01 2025-11-02 2025-11-03 2025-11-04
City
Bangalore         Cloudy                10         11         12          8
Chennai            Sunny                14         16         15         14
Kolkata    Partly Cloudy                 9          8         10         11
Mumbai          Overcast                 8          7          6          7
New Delhi          Foggy                12         10         13          9

###Pivot Grouper

In [ ]:
datas=pd.read_csv("/content/sample_data/sample_orders_dataset.csv", parse_dates=['Date'])
datas

    OrderID       Date     Category         Product  Quantity   Price
0   ORD0001 2024-03-09  Electronics          Tablet         6  290.49
1   ORD0002 2023-03-17     Clothing         T-Shirt         4  450.83
2   ORD0003 2024-10-22       Sports       Dumbbells         8  108.16
3   ORD0004 2023-10-09  Electronics          Tablet         2  439.33
4   ORD0005 2024-11-16       Sports   Tennis Racket        10   42.55
5   ORD0006 2024-10-05  Electronics      Smartphone         5   79.21
6   ORD0007 2023-07-18     Clothing         T-Shirt         8  229.82
7   ORD0008 2024-08-21     Clothing          Jacket         5  273.45
8   ORD0009 2024-06-13  Electronics      Smartphone         2  158.05
9   ORD0010 2024-06-17  Electronics          Laptop         8   67.85
10  ORD0011 2023-11-10       Beauty         Perfume         3  219.42
11  ORD0012 2023-06-13         Home            Sofa         7  145.57
12  ORD0013 2024-03-14  Electronics          Laptop         7  216.59
13  ORD0014 2024-08-23       Sports        Football         6  485.98
14  ORD0015 2024-10-13       Sports       Dumbbells         9  202.64
15  ORD0016 2023-02-21       Sports        Football         7  496.67
16  ORD0017 2023-08-09     Clothing         T-Shirt         1  186.90
17  ORD0018 2024-05-08         Home            Lamp         5   75.06
18  ORD0019 2023-08-11       Sports        Football         1  251.98
19  ORD0020 2024-07-15         Home         Bedding         1  320.74
20  ORD0021 2024-11-15  Electronics          Laptop         2  461.03
21  ORD0022 2024-07-26     Clothing        Sneakers         1  351.39
22  ORD0023 2024-08-22     Clothing        Sneakers         7  203.74
23  ORD0024 2024-06-21  Electronics          Laptop         5   61.87
24  ORD0025 2024-05-14       Sports   Tennis Racket         3  168.61
25  ORD0026 2023-09-15       Beauty      Face Cream         6  115.77
26  ORD0027 2024-01-30       Beauty         Perfume         9  202.19
27  ORD0028 2023-03-07         Home         Bedding         8  323.23
28  ORD0029 2023-07-11       Sports       Dumbbells         4  441.51
29  ORD0030 2024-04-07       Sports  Bicycle Helmet         9  251.27
30  ORD0031 2023-09-06  Electronics          Tablet         2   61.23
31  ORD0032 2024-10-22     Clothing             Hat         7  296.05
32  ORD0033 2023-10-04  Electronics          Tablet         3  360.90
33  ORD0034 2023-07-20       Beauty      Face Cream         3   59.52
34  ORD0035 2023-02-18         Home         Bedding         7  238.08
35  ORD0036 2024-04-12       Beauty      Face Cream         6  453.04
36  ORD0037 2023-05-11       Beauty         Shampoo         7  149.24
37  ORD0038 2023-12-20  Electronics      Headphones         1  166.34
38  ORD0039 2024-07-07       Beauty         Perfume        10  250.60
39  ORD0040 2024-02-09       Sports   Tennis Racket         3   48.74
40  ORD0041 2024-01-09       Sports        Football         7  298.08
41  ORD0042 2024-06-12         Home  Vacuum Cleaner         8  375.02
42  ORD0043 2023-08-18       Beauty          Lotion         5  247.46
43  ORD0044 2024-10-04       Beauty         Perfume         8  169.22
44  ORD0045 2023-10-07       Sports       Dumbbells         2  105.83
45  ORD0046 2024-02-20       Sports        Yoga Mat         5   92.42
46  ORD0047 2024-02-22       Sports       Dumbbells         5  424.08
47  ORD0048 2024-06-17       Sports       Dumbbells         6  415.70
48  ORD0049 2023-06-23       Sports       Dumbbells         4  400.67
49  ORD0050 2024-08-19       Beauty         Shampoo         8   49.53

In [ ]:
datas["Total"]=datas["Quantity"]*datas["Price"]
datas

    OrderID       Date     Category         Product  Quantity   Price    Total
0   ORD0001 2024-03-09  Electronics          Tablet         6  290.49  1742.94
1   ORD0002 2023-03-17     Clothing         T-Shirt         4  450.83  1803.32
2   ORD0003 2024-10-22       Sports       Dumbbells         8  108.16   865.28
3   ORD0004 2023-10-09  Electronics          Tablet         2  439.33   878.66
4   ORD0005 2024-11-16       Sports   Tennis Racket        10   42.55   425.50
5   ORD0006 2024-10-05  Electronics      Smartphone         5   79.21   396.05
6   ORD0007 2023-07-18     Clothing         T-Shirt         8  229.82  1838.56
7   ORD0008 2024-08-21     Clothing          Jacket         5  273.45  1367.25
8   ORD0009 2024-06-13  Electronics      Smartphone         2  158.05   316.10
9   ORD0010 2024-06-17  Electronics          Laptop         8   67.85   542.80
10  ORD0011 2023-11-10       Beauty         Perfume         3  219.42   658.26
11  ORD0012 2023-06-13         Home            Sofa         7  145.57  1018.99
12  ORD0013 2024-03-14  Electronics          Laptop         7  216.59  1516.13
13  ORD0014 2024-08-23       Sports        Football         6  485.98  2915.88
14  ORD0015 2024-10-13       Sports       Dumbbells         9  202.64  1823.76
15  ORD0016 2023-02-21       Sports        Football         7  496.67  3476.69
16  ORD0017 2023-08-09     Clothing         T-Shirt         1  186.90   186.90
17  ORD0018 2024-05-08         Home            Lamp         5   75.06   375.30
18  ORD0019 2023-08-11       Sports        Football         1  251.98   251.98
19  ORD0020 2024-07-15         Home         Bedding         1  320.74   320.74
20  ORD0021 2024-11-15  Electronics          Laptop         2  461.03   922.06
21  ORD0022 2024-07-26     Clothing        Sneakers         1  351.39   351.39
22  ORD0023 2024-08-22     Clothing        Sneakers         7  203.74  1426.18
23  ORD0024 2024-06-21  Electronics          Laptop         5   61.87   309.35
24  ORD0025 2024-05-14       Sports   Tennis Racket         3  168.61   505.83
25  ORD0026 2023-09-15       Beauty      Face Cream         6  115.77   694.62
26  ORD0027 2024-01-30       Beauty         Perfume         9  202.19  1819.71
27  ORD0028 2023-03-07         Home         Bedding         8  323.23  2585.84
28  ORD0029 2023-07-11       Sports       Dumbbells         4  441.51  1766.04
29  ORD0030 2024-04-07       Sports  Bicycle Helmet         9  251.27  2261.43
30  ORD0031 2023-09-06  Electronics          Tablet         2   61.23   122.46
31  ORD0032 2024-10-22     Clothing             Hat         7  296.05  2072.35
32  ORD0033 2023-10-04  Electronics          Tablet         3  360.90  1082.70
33  ORD0034 2023-07-20       Beauty      Face Cream         3   59.52   178.56
34  ORD0035 2023-02-18         Home         Bedding         7  238.08  1666.56
35  ORD0036 2024-04-12       Beauty      Face Cream         6  453.04  2718.24
36  ORD0037 2023-05-11       Beauty         Shampoo         7  149.24  1044.68
37  ORD0038 2023-12-20  Electronics      Headphones         1  166.34   166.34
38  ORD0039 2024-07-07       Beauty         Perfume        10  250.60  2506.00
39  ORD0040 2024-02-09       Sports   Tennis Racket         3   48.74   146.22
40  ORD0041 2024-01-09       Sports        Football         7  298.08  2086.56
41  ORD0042 2024-06-12         Home  Vacuum Cleaner         8  375.02  3000.16
42  ORD0043 2023-08-18       Beauty          Lotion         5  247.46  1237.30
43  ORD0044 2024-10-04       Beauty         Perfume         8  169.22  1353.76
44  ORD0045 2023-10-07       Sports       Dumbbells         2  105.83   211.66
45  ORD0046 2024-02-20       Sports        Yoga Mat         5   92.42   462.10
46  ORD0047 2024-02-22       Sports       Dumbbells         5  424.08  2120.40
47  ORD0048 2024-06-17       Sports       Dumbbells         6  415.70  2494.20
48  ORD0049 2023-06-23       Sports       Dumbbells         4  400.67  1602.68
49  ORD0050 2024-08-19       Beauty         Shampoo         8   49.53   396.24

In [ ]:
pivot=pd.pivot_table(
datas,
index=pd.Grouper(key="Date",freq='M'),
columns="Category",
values="Total",
aggfunc="sum"
)
pivot

/tmp/ipython-input-2913894302.py:3: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  index=pd.Grouper(key="Date",freq='M'),

Category     Beauty  Clothing  Electronics     Home   Sports
Date
2023-02-28      NaN       NaN          NaN  1666.56  3476.69
2023-03-31      NaN   1803.32          NaN  2585.84      NaN
2023-05-31  1044.68       NaN          NaN      NaN      NaN
2023-06-30      NaN       NaN          NaN  1018.99  1602.68
2023-07-31   178.56   1838.56          NaN      NaN  1766.04
2023-08-31  1237.30    186.90          NaN      NaN   251.98
2023-09-30   694.62       NaN       122.46      NaN      NaN
2023-10-31      NaN       NaN      1961.36      NaN   211.66
2023-11-30   658.26       NaN          NaN      NaN      NaN
2023-12-31      NaN       NaN       166.34      NaN      NaN
2024-01-31  1819.71       NaN          NaN      NaN  2086.56
2024-02-29      NaN       NaN          NaN      NaN  2728.72
2024-03-31      NaN       NaN      3259.07      NaN      NaN
2024-04-30  2718.24       NaN          NaN      NaN  2261.43
2024-05-31      NaN       NaN          NaN   375.30   505.83
2024-06-30      NaN       NaN      1168.25  3000.16  2494.20
2024-07-31  2506.00    351.39          NaN   320.74      NaN
2024-08-31   396.24   2793.43          NaN      NaN  2915.88
2024-10-31  1353.76   2072.35       396.05      NaN  2689.04
2024-11-30      NaN       NaN       922.06      NaN   425.50

##Melt

Melt allows to transform or reshape the data frame.

In [ ]:
import pandas as pd
data=pd.read_csv("/content/sample_data/weather_dataset (3).csv")
data

,Date,City,Temperature,Humidity,Wind Speed (km/h),Weather Condition
0,2025-11-01,New Delhi,28,45,12,Sunny
1,2025-11-01,Mumbai,32,70,8,Humid
2,2025-11-01,Bangalore,25,65,10,Cloudy
3,2025-11-01,Chennai,33,75,14,Hot
4,2025-11-01,Kolkata,30,68,9,Partly Cloudy
5,2025-11-02,New Delhi,27,48,10,Sunny
6,2025-11-02,Mumbai,31,72,7,Humid
7,2025-11-02,Bangalore,24,60,11,Drizzle
8,2025-11-02,Chennai,34,78,16,Hot
9,2025-11-02,Kolkata,29,70,8,Rainy
10,2025-11-03,New Delhi,26,50,13,Clear
11,2025-11-03,Mumbai,30,68,6,Sunny
12,2025-11-03,Bangalore,23,66,12,Thunderstorms
13,2025-11-03,Chennai,32,80,15,Humid
14,2025-11-03,Kolkata,28,72,10,Cloudy
15,2025-11-04,New Delhi,25,55,9,Foggy
16,2025-11-04,Mumbai,29,75,7,Overcast
17,2025-11-04,Bangalore,24,64,8,Cloudy
18,2025-11-04,Chennai,33,77,14,Sunny
19,2025-11-04,Kolkata,30,69,11,Partly Cloudy

In [ ]:
pd.melt(data,id_vars=['Date'])

          Date           variable          value
0   2025-11-01               City      New Delhi
1   2025-11-01               City         Mumbai
2   2025-11-01               City      Bangalore
3   2025-11-01               City        Chennai
4   2025-11-01               City        Kolkata
..         ...                ...            ...
95  2025-11-04  Weather Condition          Foggy
96  2025-11-04  Weather Condition       Overcast
97  2025-11-04  Weather Condition         Cloudy
98  2025-11-04  Weather Condition          Sunny
99  2025-11-04  Weather Condition  Partly Cloudy

[100 rows x 3 columns]

In [ ]:
import pandas as pd
data=pd.read_csv("/content/sample_data/weather_dataset (3).csv")
data

,Date,City,Temperature,Humidity,Wind Speed (km/h),Weather Condition
0,2025-11-01,New Delhi,28,45,12,Sunny
1,2025-11-01,Mumbai,32,70,8,Humid
2,2025-11-01,Bangalore,25,65,10,Cloudy
3,2025-11-01,Chennai,33,75,14,Hot
4,2025-11-01,Kolkata,30,68,9,Partly Cloudy
5,2025-11-02,New Delhi,27,48,10,Sunny
6,2025-11-02,Mumbai,31,72,7,Humid
7,2025-11-02,Bangalore,24,60,11,Drizzle
8,2025-11-02,Chennai,34,78,16,Hot
9,2025-11-02,Kolkata,29,70,8,Rainy
10,2025-11-03,New Delhi,26,50,13,Clear
11,2025-11-03,Mumbai,30,68,6,Sunny
12,2025-11-03,Bangalore,23,66,12,Thunderstorms
13,2025-11-03,Chennai,32,80,15,Humid
14,2025-11-03,Kolkata,28,72,10,Cloudy
15,2025-11-04,New Delhi,25,55,9,Foggy
16,2025-11-04,Mumbai,29,75,7,Overcast
17,2025-11-04,Bangalore,24,64,8,Cloudy
18,2025-11-04,Chennai,33,77,14,Sunny
19,2025-11-04,Kolkata,30,69,11,Partly Cloudy

In [ ]:
melted=pd.melt(
    data,
    id_vars=["City","Date","Weather Condition"],
    value_vars=['Temperature', 'Humidity'],
    var_name='Weather_Parameter',
    value_name='Reading'
)
melted

         City        Date Weather Condition Weather_Parameter  Reading
0   New Delhi  2025-11-01             Sunny       Temperature       28
1      Mumbai  2025-11-01             Humid       Temperature       32
2   Bangalore  2025-11-01            Cloudy       Temperature       25
3     Chennai  2025-11-01               Hot       Temperature       33
4     Kolkata  2025-11-01     Partly Cloudy       Temperature       30
5   New Delhi  2025-11-02             Sunny       Temperature       27
6      Mumbai  2025-11-02             Humid       Temperature       31
7   Bangalore  2025-11-02           Drizzle       Temperature       24
8     Chennai  2025-11-02               Hot       Temperature       34
9     Kolkata  2025-11-02             Rainy       Temperature       29
10  New Delhi  2025-11-03             Clear       Temperature       26
11     Mumbai  2025-11-03             Sunny       Temperature       30
12  Bangalore  2025-11-03     Thunderstorms       Temperature       23
13    Chennai  2025-11-03             Humid       Temperature       32
14    Kolkata  2025-11-03            Cloudy       Temperature       28
15  New Delhi  2025-11-04             Foggy       Temperature       25
16     Mumbai  2025-11-04          Overcast       Temperature       29
17  Bangalore  2025-11-04            Cloudy       Temperature       24
18    Chennai  2025-11-04             Sunny       Temperature       33
19    Kolkata  2025-11-04     Partly Cloudy       Temperature       30
20  New Delhi  2025-11-01             Sunny          Humidity       45
21     Mumbai  2025-11-01             Humid          Humidity       70
22  Bangalore  2025-11-01            Cloudy          Humidity       65
23    Chennai  2025-11-01               Hot          Humidity       75
24    Kolkata  2025-11-01     Partly Cloudy          Humidity       68
25  New Delhi  2025-11-02             Sunny          Humidity       48
26     Mumbai  2025-11-02             Humid          Humidity       72
27  Bangalore  2025-11-02           Drizzle          Humidity       60
28    Chennai  2025-11-02               Hot          Humidity       78
29    Kolkata  2025-11-02             Rainy          Humidity       70
30  New Delhi  2025-11-03             Clear          Humidity       50
31     Mumbai  2025-11-03             Sunny          Humidity       68
32  Bangalore  2025-11-03     Thunderstorms          Humidity       66
33    Chennai  2025-11-03             Humid          Humidity       80
34    Kolkata  2025-11-03            Cloudy          Humidity       72
35  New Delhi  2025-11-04             Foggy          Humidity       55
36     Mumbai  2025-11-04          Overcast          Humidity       75
37  Bangalore  2025-11-04            Cloudy          Humidity       64
38    Chennai  2025-11-04             Sunny          Humidity       77
39    Kolkata  2025-11-04     Partly Cloudy          Humidity       69

##Cross tab or contingency table

In pandas, pd.crosstab() is used to compute a cross-tabulation of two or more factors. It’s often used for analyzing categorical variables, similar to a contingency table in statistics.

syntax:

pd.crosstab(index, columns, values=None, aggfunc=None, margins=False, margins_name='All')

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/survey_crosstab.csv")
df

   RespondentID  Gender AgeGroup Preferred_Device
0             1    Male    18-25           Laptop
1             2  Female    26-35           Mobile
2             3    Male    18-25           Tablet
3             4  Female    18-25           Mobile
4             5    Male    26-35           Laptop
5             6  Female    18-25           Mobile
6             7    Male    36-45           Laptop
7             8  Female    26-35           Tablet
8             9    Male    26-35           Mobile
9            10  Female    36-45           Laptop

In [ ]:
#Create cros  tabulation
ct=pd.crosstab(df["Gender"],df["Preferred_Device"])
print(ct)

Preferred_Device  Laptop  Mobile  Tablet
Gender
Female                 1       3       1
Male                   3       1       1

In [ ]:
# Cross-tab of AgeGroup vs Preferred_Device with totals:
ct=pd.crosstab(df["AgeGroup"],df["Preferred_Device"],margins=True,margins_name="Total")
print(ct)

Preferred_Device  Laptop  Mobile  Tablet  Total
AgeGroup
18-25                  1       2       1      4
26-35                  1       2       1      4
36-45                  2       0       0      2
Total                  4       4       2     10

##to_datetime()

to_datetime function is very useful in pandas to convert any string date to type datetime

In [ ]:
pd.to_datetime(["05/01/2016"],dayfirst=True)

DatetimeIndex(['2016-01-05'], dtype='datetime64[ns]', freq=None)

In [ ]:
dates = ['2023-01-01', 'invalid_date', '2023-03-30']
pd.to_datetime(dates, errors='coerce')

DatetimeIndex(['2023-01-01', 'NaT', '2023-03-30'], dtype='datetime64[ns]', freq=None)

In [ ]:
import pandas as pd
data=pd.read_csv("/content/sample_data/weather_dataset (3).csv")
data

,Date,City,Temperature,Humidity,Wind Speed (km/h),Weather Condition
0,2025-11-01,New Delhi,28,45,12,Sunny
1,2025-11-01,Mumbai,32,70,8,Humid
2,2025-11-01,Bangalore,25,65,10,Cloudy
3,2025-11-01,Chennai,33,75,14,Hot
4,2025-11-01,Kolkata,30,68,9,Partly Cloudy
5,2025-11-02,New Delhi,27,48,10,Sunny
6,2025-11-02,Mumbai,31,72,7,Humid
7,2025-11-02,Bangalore,24,60,11,Drizzle
8,2025-11-02,Chennai,34,78,16,Hot
9,2025-11-02,Kolkata,29,70,8,Rainy
10,2025-11-03,New Delhi,26,50,13,Clear
11,2025-11-03,Mumbai,30,68,6,Sunny
12,2025-11-03,Bangalore,23,66,12,Thunderstorms
13,2025-11-03,Chennai,32,80,15,Humid
14,2025-11-03,Kolkata,28,72,10,Cloudy
15,2025-11-04,New Delhi,25,55,9,Foggy
16,2025-11-04,Mumbai,29,75,7,Overcast
17,2025-11-04,Bangalore,24,64,8,Cloudy
18,2025-11-04,Chennai,33,77,14,Sunny
19,2025-11-04,Kolkata,30,69,11,Partly Cloudy

In [ ]:
print("Original DataFrame:")
print(data)
# Use applymap() to increase all numeric values by 1.0 (if applicable)
# We must exclude the 'City' column (non-numeric), or handle non-numeric safely
data_numeric=data.select_dtypes(include="number")
data[data_numeric.columns]=data_numeric.applymap(lambda x:x+1)
print("DataFrame after applymap (numeric values +1):")
data

Original DataFrame:
          Date       City  Temperature  Humidity  Wind Speed (km/h)  \
0   2025-11-01  New Delhi           28        45                 12
1   2025-11-01     Mumbai           32        70                  8
2   2025-11-01  Bangalore           25        65                 10
3   2025-11-01    Chennai           33        75                 14
4   2025-11-01    Kolkata           30        68                  9
5   2025-11-02  New Delhi           27        48                 10
6   2025-11-02     Mumbai           31        72                  7
7   2025-11-02  Bangalore           24        60                 11
8   2025-11-02    Chennai           34        78                 16
9   2025-11-02    Kolkata           29        70                  8
10  2025-11-03  New Delhi           26        50                 13
11  2025-11-03     Mumbai           30        68                  6
12  2025-11-03  Bangalore           23        66                 12
13  2025-11-03    Chennai           32        80                 15
14  2025-11-03    Kolkata           28        72                 10
15  2025-11-04  New Delhi           25        55                  9
16  2025-11-04     Mumbai           29        75                  7
17  2025-11-04  Bangalore           24        64                  8
18  2025-11-04    Chennai           33        77                 14
19  2025-11-04    Kolkata           30        69                 11

   Weather Condition
0              Sunny
1              Humid
2             Cloudy
3                Hot
4      Partly Cloudy
5              Sunny
6              Humid
7            Drizzle
8                Hot
9              Rainy
10             Clear
11             Sunny
12     Thunderstorms
13             Humid
14            Cloudy
15             Foggy
16          Overcast
17            Cloudy
18             Sunny
19     Partly Cloudy
DataFrame after applymap (numeric values +1):

/tmp/ipython-input-2761379961.py:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  data[data_numeric.columns]=data_numeric.applymap(lambda x:x+1)

,Date,City,Temperature,Humidity,Wind Speed (km/h),Weather Condition
0,2025-11-01,New Delhi,29,46,13,Sunny
1,2025-11-01,Mumbai,33,71,9,Humid
2,2025-11-01,Bangalore,26,66,11,Cloudy
3,2025-11-01,Chennai,34,76,15,Hot
4,2025-11-01,Kolkata,31,69,10,Partly Cloudy
5,2025-11-02,New Delhi,28,49,11,Sunny
6,2025-11-02,Mumbai,32,73,8,Humid
7,2025-11-02,Bangalore,25,61,12,Drizzle
8,2025-11-02,Chennai,35,79,17,Hot
9,2025-11-02,Kolkata,30,71,9,Rainy
10,2025-11-03,New Delhi,27,51,14,Clear
11,2025-11-03,Mumbai,31,69,7,Sunny
12,2025-11-03,Bangalore,24,67,13,Thunderstorms
13,2025-11-03,Chennai,33,81,16,Humid
14,2025-11-03,Kolkata,29,73,11,Cloudy
15,2025-11-04,New Delhi,26,56,10,Foggy
16,2025-11-04,Mumbai,30,76,8,Overcast
17,2025-11-04,Bangalore,25,65,9,Cloudy
18,2025-11-04,Chennai,34,78,15,Sunny
19,2025-11-04,Kolkata,31,70,12,Partly Cloudy